export const registerPageProps = {
    title: "Registrace",
    meta_content: "Registrační formulář.",
    form_title: "Registrace",
    name: "Jméno",
    form_name: "name",
    email: "Email",
    password: "Heslo",
    re_password: "Heslo pro kontrolu",
    form_username: "name",
    form_email: "email",
    form_re_password: "re_password",
    form_password: "password",
    form_button: "Registrovat se",
    form_link: "Máte zde účet?",
    form_link_href: "/prihlaseni",
    form_link_text: "Přihlášení", 
}         